openapi: 3.0.0
info:
  title: AssesmenWebService2
  version: 1.0.0
servers:
  - url: https://130.162.195.228/mhs714220020
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
paths:
  /regis:
    post:
      tags:
        - Authentication
      summary: User Registration
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: audya
                email: audy@gmail.com
                password: audy123
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /login:
    post:
      tags:
        - Authentication
      summary: User Login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: audya
                password: audy123
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}

  /pelukis:
    post:
      tags:
        - Pelukis Management
      summary: Create a New Pelukis
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                nama: awwdyyaa nasywa
                alamat: wajo
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Pelukis Management
      summary: Get All Pelukis
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}

  /pelukis/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          example: 1
    get:
      tags:
        - Pelukis Management
      summary: Get Pelukis by ID
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  nama:
                    type: string
                  alamat:
                    type: string
                example:
                  id: 1
                  nama: awwdyyaa nasywa
                  alamat: wajo
    put:
      tags:
        - Pelukis Management
      summary: Update Pelukis
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                nama: audyardha
                alamat: Cokro
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - Pelukis Management
      summary: Delete Pelukis
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}

  /karya:
    post:
      tags:
        - Karya Management
      summary: Create a New Karya
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                judul: Nasywa
                pelukis_id: 16
                tahun_dibuat: 2024
                media: kanvas
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Karya Management
      summary: Get All Karya
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}

  /karya/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          example: 1
    get:
      tags:
        - Karya Management
      summary: Get Karya by ID
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  judul:
                    type: string
                  pelukis_id:
                    type: integer
                  tahun_dibuat:
                    type: integer
                  media:
                    type: string
              example:
                id: 1
                judul: Nasywa
                pelukis_id: 16
                tahun_dibuat: 2024
                media: kanvas
    put:
      tags:
        - Karya Management
      summary: Update Karya
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                judul: nasywaja
                pelukis_id: 16
                tahun_dibuat: 2021
                media: Lukis
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - Karya Management
      summary: Delete Karya
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
